default:
  golem_name: lipidomics3
  golem_version: 0.0.0.9000
  app_prod: no
  # mzML files are large, so the Shiny default of 5 MB is far too small.
  max_upload_size_mb: 8192
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
